### ISSUE TITLE
Classes & Instances, outdated information

### ISSUE THREAD

**Issue by ObieMunoz** [learn-co-curriculum/phase-1-classes-and-instances#1]
### Canvas Link

https://learning.flatironschool.com/courses/4541/pages/classes-and-instances?module_item_id=310528

### Concern

```
Currently, there is no official way to make a property private - all class and object properties are exposed as we see above. One common convention, however, is to include an underscore at the beginning of the property name to indicate those properties are not intended to be accessed from outside the class:

class Transaction {
  constructor(amount, date, memo) {
    this._amount = amount;
    this._date = date;
    this._memo = memo;
  }
}
Now, it is still possible to modify these properties, the amount property name just changed to _amount. The above class, setup, however, suggests that these properties should only be accessed or changed through class methods, not directly.

Implementing private properties is planned in future versions of JavaScript (Links to an external site.), and will use a # symbol to indicate a property is private.
```

The above section is outdated and the hashtag functionality is now available in JavaScript. See the following MDN Web Documentation:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

### Suggested Changes

Change the section of the Canvas lesson discussing the deprecated underscore method to show how to use private properties. 

The following code snippet:

```
class Transaction {
  constructor(amount, date, memo) {
    this._amount = amount;
    this._date = date;
    this._memo = memo;
  }
}
```

could be changed to:

```
class Transaction {
  #amount;
  #date;
  #memo;

  constructor(amount, date, memo) {
    this.#amount = amount;
    this.#date = date;
    this.#memo = memo;
  }
}
```

This class setup implements the # symbol to indicate a property is private and have that privacy enforced by JavaScript.

**Comment by lizbur10** [comment]
Hi @ObieMunoz ! Thank you for bringing this to our attention! We are working on updating this lesson and the lab that follows.

Thanks for contributing to the Flatiron School curriculum 💙
